version: '3'
services:
  app:
    build: .
    entrypoint: bin/entrypoint.sh
    command: /bin/bash -c 'bundle exec rails s -b 0.0.0.0 -p 3000'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - DEV_DATABASE_HOST=db
      - DATABASE_URL=postgres://root@db:5432/database-dev
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database-dev
      - POSTGRES_USER=root
